name = "CategoricalInterventions"
uuid = "41d3b195-a1da-4a54-ad81-3d9bd0dfc9b1"
version = "0.1.0"
authors = ["Simon Frost and contributors"]

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"

[extensions]
CategoricalInterventionsDiffEqCallbacksExt = "DiffEqCallbacks"

[compat]
AlgebraicPetri = "0.10"
Catlab = "0.16, 0.17"
DiffEqCallbacks = "2, 3, 4"
LabelledArrays = "1"
OrdinaryDiffEq = "6"
julia = "1.10"

[extras]
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DiffEqCallbacks", "AlgebraicPetri", "LabelledArrays", "OrdinaryDiffEq"]
