# Generates docs/src/verified.md and fails if any listed Lean theorem is missing.
const LEDGER = [
    ("Programs compose associatively with the empty program as identity", "compose", ["compose_assoc", "compose_nil_left", "compose_nil_right"], "test/laws.jl"),
    ("Under a partial commutative monoid, the order of atoms never matters", "fold", ["fold_perm", "foldAt_perm", "apply_comm"], "test/laws.jl"),
    ("For the shipped (pairwise) algebras, a program is conflict-free iff every pair of overlapping same-target atoms combines", "conflicts", ["conflictFree_of_pairwise", "pairwise_of_conflictFree", "foldList_isSome_iff_pairwise"], "test/laws.jl"),
    ("Different targets never conflict; disjoint supports never conflict", "conflicts", ["different_target_compatible", "disjoint_compatible"], "test/core.jl"),
    ("Factors of a conflict-free composite are conflict-free", "compose", ["conflictFree_append_left", "conflictFree_append_right"], "test/laws.jl"),
    ("Set-then-scale is a partial commutative monoid; two absolute assignments conflict", "Affine", ["affine_pcm", "fold_affine_isSome_iff"], "test/core.jl"),
    ("Under set-then-scale the absolute value is applied first, then the relative product", "Affine", ["affine_action", "affine_act_mul_of_relative"], "test/laws.jl"),
    ("Every time inside a span lies in exactly one epoch, and for span-only programs the active set is constant on an epoch", "epochs", ["epoch_cover", "active_const_on_epoch"], "test/core.jl"),
    ("Adding atoms only refines the epochs: each new epoch lies inside every old epoch it meets", "epochs", ["epochs_refine"], "test/laws.jl"),
    ("A program is a persistent narrative (sheaf): A[a,b] = A[a,p] ∩ A[p,b]", "persistent", ["persistent_glue", "persistent_antitone"], "test/laws.jl"),
    ("A program is a cumulative narrative (cosheaf): C[a,b] = C[a,p] ∪ C[p,b] and C[a,p] ∩ C[p,b] = C[p,p]", "cumulative", ["cumulative_union", "cumulative_inter_eq_point", "cumulative_monotone"], "test/laws.jl"),
    ("Supports are order-convex", "Span, Instant", ["support_ordConnected"], "test/core.jl"),
    ("The empty program does nothing; outside every support the schedule is unchanged", "apply", ["apply_nil", "apply_local"], "test/laws.jl"),
    ("When P ⊕ Q is conflict-free, applying P then Q equals applying P ⊕ Q (acting algebras; under Affine when Q is purely relative)", "apply", ["apply_append", "apply_append_affine"], "test/laws.jl"),
    ("Applying a program commutes with restricting or resampling the schedule", "apply, sample", ["apply_pullback", "grid_preimage_span", "apply_discrete_eq"], "test/laws.jl"),
    ("For span-only programs the schedule is constant on each epoch when the baseline is", "apply", ["apply_const_on_epoch"], "test/core.jl"),
    ("For span-only programs with a constant baseline, holding each parameter from one event to the next reproduces the schedule (callback correctness)", "lower, hold_last", ["lower_eq_apply"], "test/laws.jl"),
    ("Transfers conserve the total", "Transfer", ["transfer_preserves_sum"], "test/models.jl"),
    ("Discrete-time pulses are applied before the update", "simulate", ["pulse_before_update", "discreteStep_no_pulse"], "test/models.jl"),
    ("Flows on function-valued models are parameter intervals on a wrapped model", "augment_flow", ["augment_restrict"], "test/models.jl"),
    ("Pushforward is functorial and preserves conflict-freeness when injective on the targets used", "pushforward", ["pushforward_comp", "conflictFree_pushforward_of_injOn"], "test/core.jl"),
    ("Lifting to a stratified model is functorial, preserves conflict-freeness, and acts stratum-wise", "lift", ["lift_comp", "conflictFree_lift_iff'", "apply_lift"], "test/core.jl"),
    ("A flow is a parameter intervention on the augmented model, unchanged on the original targets", "augment", ["augment_restrict", "augment_conflictFree_iff"], "test/models.jl"),
    ("Inferring a program from a program's own output returns that output when re-applied", "infer", ["infer_putget", "infer_putget_grid_step"], "test/core.jl"),
]

function generate_ledger(root::AbstractString)
    lean_dir = joinpath(root, "proofs", "CategoricalInterventionsProofs")
    sources = read.(filter(f -> endswith(f, ".lean"), readdir(lean_dir; join=true)), String)
    theorems = Set{String}()
    for src in sources, m in eachmatch(r"^(?:theorem|lemma)\s+([A-Za-z0-9_'.]+)"m, src)
        push!(theorems, m.captures[1])
    end
    missing = String[]
    io = IOBuffer()
    println(io, "# [Verified properties](@id verified)\n")
    println(io, "Every claim the documentation makes about the algebra of programs, with the ")
    println(io, "Lean theorem that proves it and the Julia test that exercises it. The Lean ")
    println(io, "sources live in `proofs/` and build with `make build` (Lean 4.30.0, Mathlib ")
    println(io, "v4.30.0). This page is generated by `docs/ledger.jl`, which fails the build ")
    println(io, "if a listed theorem is absent from the sources.\n")
    println(io, "Lean verifies the algebra of programs, their action on schedules, and the ")
    println(io, "lowering algorithm; it does not verify the ODE solver or Catlab.\n")
    println(io, "| Claim | Definition | Lean | Test |")
    println(io, "|---|---|---|---|")
    for (claim, def, thms, test) in LEDGER
        for t in thms
            t in theorems || push!(missing, t)
        end
        println(io, "| ", claim, " | `", def, "` | ", join(("`$t`" for t in thms), ", "), " | `", test, "` |")
    end
    println(io, "\nTheorems in the Lean sources: ", length(theorems), ".")
    isempty(missing) || error("Ledger entries without a Lean theorem: " * join(missing, ", "))
    write(joinpath(root, "docs", "src", "verified.md"), String(take!(io)))
    return length(theorems)
end
